config/routes.rb
Rails.application.routes.draw do
  resources :moves, except: :destroy
  resources :wrestlers, except: :destroy 
  resources :users
  resources :favorite_moves, only: [:index, :new, :create]
  resources :favorite_wrestlers, only: [:index, :new, :create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/areyousure', to: 'users#areyousure'
  delete '/logout', to: 'sessions#destroy'
  root 'sessions#welcome'



  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorite_moves
    has_many :favorite_wrestlers
    has_many :wrestlers, through: :favorite_wrestlers
    has_many :moves, through: :favorite_moves
    validates :name, :bio, :email, :password, :presence => true
    validates :name, uniqueness: { case_sensitive: false }
    has_secure_password

#next three methods find a users top 5 moves
    def user_favorite_moves
        FavoriteMove.all.select do |fav|
            fav.user == self 
        end 
    end 

    def user_fav_move_by_rating
        user_favorite_moves.sort do |a, b|
            a.rating <=> b.rating
        end
    end

    def user_fav_moves_top_five_rated
        user_fav_move_by_rating.reverse[0..4]
    end 

#next three methods find a users top 5 wrestlers
    def user_favorite_wrestlers
        FavoriteWrestler.all.select do |fav|
            fav.user == self 
        end 
    end 

    def user_fav_wrestler_by_rating
        user_favorite_wrestlers.sort do |a, b|
            a.rating <=> b.rating
        end
    end

    def user_fav_wrestlers_top_five_rated
        user_fav_wrestler_by_rating.reverse[0..4]
    end     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorized
    skip_before_action :authorized, only: [:new, :create] 
    
    def index
        @users = User.all
        get_current_user
    end 

    def show
        get_current_user.reload
        find_user
    end 

    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            @errors = @user.errors.full_messages
            render :new
        end 
    end 

    def edit
        @user = get_current_user
    end

    def update
        @user = get_current_user
        @user.assign_attributes(user_params)
        if @user.valid?
            @user.save
            redirect_to user_path(@user)
        else 
            @errors = @user.errors.full_messages
            render :edit
        end 
    end

    def areyousure
        get_current_user
        render :areyousure
    end 

    def destroy
        get_current_user.destroy
        FavoriteMove.clean_out_database
        FavoriteWrestler.clean_out_database
        redirect_to '/'
    end 

    private
    def find_user
        @user = User.find(params[:id])
    end 

    def user_params
        params.require(:user).permit(:name, :bio, :email, :password)
    end

    def get_current_user
        @current_user = User.find_by(id: session[:user_id])
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/areyousure.html.erb
<h1> Are you sure you want to delete your User Page? </h1>
<%= button_to "Yes!", "/users/#{@current_user.id}", method: :delete %>
<%= button_to "No!", users_path(@current_user), method: :get %><br>
<img src="https://pa1.narvii.com/6493/dbc10debb7831fdc5acae6e9f63f9ae876014be9_hq.gif" alt="ref">

app/views/users/edit.html.erb
<h1> Update Your User Page </h1>

<% if @errors %>
    <% @errors.each do |error| %>
        <p><%= error %></p>
    <% end %>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :name, 'Username:' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :description, 'Short Bio:' %><br>
    <%= f.text_area :bio %><br>
    <%= f.label :email, 'Email:' %><br>
    <%= f.text_field :email %><br>
    <%= f.label :password, 'Password:' %><br>
    <%= f.password_field :password %><br>
    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class="index">

<h1> User Profiles: </h1>

<% @users.each do |user| %>
<h3> <%= link_to user.name, user_path(user.id) %> </h3>
<% end %>
</div>

app/views/users/new.html.erb
<h1> Create a User Page </h1>

<% if @errors %>
    <% @errors.each do |error| %>
        <p><%= error %></p>
    <% end %>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :name, 'Username:' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :description, 'Short Bio:' %><br>
    <%= f.text_area :bio %><br>
    <%= f.label :email, 'Email:' %><br>
    <%= f.text_field :email %><br>
    <%= f.label :password, 'Password:' %><br>
    <%= f.password_field :password %><br>
    <%= f.submit %>
<% end %>
<hr>
<h3>Already have a user page? <%= button_to "Login", '/login', method: :get%></h3>

app/views/users/show.html.erb
<div class="index">
<% if @current_user.id == @user.id %>
    <h3> Welcome! </h3>
<% end %>

<h1>Name: <%= @user.name %></h1>
<h1>Bio: <%= @user.bio %></h1>

<% unless @user.user_fav_wrestlers_top_five_rated == [] %>
    <div>
        <img style="padding:-40px" src="<%=@user.user_fav_wrestlers_top_five_rated[0].wrestler.img_url%>" alt="wrestler">
    </div>
<% end %>

<!-- highest rated wrestlers -->

<h3> Top 5 Highest Rated Wrestlers! </h3>

<% if @user.user_fav_wrestlers_top_five_rated == [] %>
    <p> User hasn't added any favorites yet. </p>
<% else %>
    <ol>
        <% @user.user_fav_wrestlers_top_five_rated.each do |fav| %>
            <li>
                <%=fav.wrestler.name%> -- Rating: <%=fav.rating%>
            </li>
        <% end %>
    </ol>
<% end %>
<%= link_to "See Wrestlers", wrestlers_path %>

<!-- highest rated moves -->

<h3> Top 5 Highest Rated Moves! </h3>

<%if @user.user_fav_moves_top_five_rated == []%>
    <p>User hasn't added any favorites yet.</p>
<% else %>
    <ol>
        <% @user.user_fav_moves_top_five_rated.each do |fav| %>
            <li>
                <%=fav.move.name%> -- Rating: <%=fav.rating%>
            </li>
        <% end %>
    </ol>
<% end %>
<%= link_to "See Moves", moves_path %><br><br>
<hr>

<% if @current_user.id == @user.id %>
    <%= link_to "Update User Page", edit_user_path, method: :get, class: "ui left attached button"%>
    <%= link_to "Delete User Page", areyousure_path, method: :get, class: "right attached ui button" %>
    
<% end %>

</div>