config/routes.rb
Rails.application.routes.draw do
  resources :moves, except: :destroy
  resources :wrestlers, except: :destroy 
  resources :users
  resources :favorite_moves, only: [:index, :new, :create]
  resources :favorite_wrestlers, only: [:index, :new, :create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/areyousure', to: 'users#areyousure'
  delete '/logout', to: 'sessions#destroy'
  root 'sessions#welcome'



  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/move.rb
class Move < ApplicationRecord
    has_many :favorite_moves
    has_many :users, through: :favorite_moves
    validates :name, :description, :presence => true

    def self.sort_move_by_name
        self.all.sort do |a, b|
            a.name <=> b.name
        end
    end 

    def get_move_favs
        FavoriteMove.all.select do |fav|
          fav.move.id == self.id 
        end 
    end 
    
    def move_average_rating
        ratings = get_move_favs.map do |fav|
            fav.rating
        end 
        ratings.sum / ratings.length.to_f
    end 

    def get_move_comments
        move_comments = get_move_favs.map do |fav|
            "#{fav.user.name} commented: #{fav.comments}"
        end 
        move_comments.reverse
    end 
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
    before_action :authorized
    skip_before_action :authorized, only: [:index, :show]

    def index
        @moves = Move.sort_move_by_name
        get_random_move
    end 

    def show
        get_current_user 
        find_move
        session[:move_id] = params[:id]
        get_random_move
    end 

    def new
        @move = Move.new
    end 

    def create
        @move = Move.new(move_params)
        if @move.valid?
            @move.save
            redirect_to move_path(@move)
        else
            @errors = @move.errors.full_messages
            render :new 
        end 
    end 

    def edit
        find_move
    end

    def update
        find_move.assign_attributes(move_params)      
        if @move.valid?
            @move.save
            redirect_to move_path(@move)
        else
            @errors = @move.errors.full_messages
            render :new 
        end 
    end

    private
    def find_move
        @move = Move.find(params[:id])
    end 

    def move_params
        params.require(:move).permit(:name, :description, :img_url)
    end 

    def get_current_user
        @current_user = User.find_by(id: session[:user_id])
    end 

    def get_random_move
        @random_move = Move.random_sample
    end 
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/edit.html.erb
<h1> Edit <%= @move.name %> </h1>

<%if @errors%>
    <%@errors.each do |error|%>
        <p><%=error%></p>
    <%end%>
<%end%>

<%= form_for @move do |f| %>
    <%= f.label :name, 'Move Name:' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :description, 'Description:' %><br>
    <%= f.text_area :description %><br>
    <%= f.label :img_url, 'Image URL:' %><br>
    <%= f.text_field :img_url %><br>
    <%= f.submit %>
<% end %>

<p><%= link_to "Back to Wrestling Moves", moves_path %> </p>

app/views/moves/index.html.erb
<div class="index">


<%= link_to "Add New Move", new_move_path,:class => "ui left attached button" %>
<%= link_to "Random Move!", move_path(@random_move), :class => "ui right attached button" %>

<h1> Moves:</h1>

<% @moves.each do |move| %>
    <h3> <%= link_to move.name, move_path(move.id) %> </h3>
<% end %>
</div>

app/views/moves/new.html.erb
<h1> Add a Wrestling Move to the Website </h1>

<%if @errors%>
    <%@errors.each do |error|%>
        <p><%=error%></p>
    <%end%>
<%end%>

<%= form_for @move do |f| %>
    <%= f.label :name, 'Move Name:' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :description, 'Description:' %><br>
    <%= f.text_area :description %><br>
    <%= f.label :img_url, 'Image URL:' %><br>
    <%= f.text_field :img_url %><br>
    <%= f.submit %>
<% end %>

<p><%= link_to "Back to Wrestling Moves", moves_path %> </p>

app/views/moves/show.html.erb
<div class="index">

    <%= link_to "Random Move!", move_path(@random_move), class: "ui button" %>

    <h1>Name: <%= @move.name %></h1>
    <h3>Description: <%= @move.description %></h3>
    <h3>Average User Rating: <%= @move.move_average_rating %></h3>

    <img src=<%= @move.img_url %> alt="move" >

    <% if @current_user %>
        <%= button_to "Add to Favorites", new_favorite_move_path, method: :get, class: "positive ui button"%><br>
        <p><%= link_to "Edit #{@move.name}", edit_move_path %> </p>
    <% end %>

    <h3>Comment Feed!</h3>
         <% @move.get_move_comments.each do |comment| %>
        <p><%= comment %></p>
    <% end %>

</div>