config/routes.rb
Rails.application.routes.draw do
  resources :moves, except: :destroy
  resources :wrestlers, except: :destroy 
  resources :users
  resources :favorite_moves, only: [:index, :new, :create]
  resources :favorite_wrestlers, only: [:index, :new, :create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/areyousure', to: 'users#areyousure'
  delete '/logout', to: 'sessions#destroy'
  root 'sessions#welcome'



  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wrestler.rb
class Wrestler < ApplicationRecord
    has_many :favorite_wrestlers
    has_many :users, through: :favorite_wrestlers
    validates :name, :bio, :presence => true


    def self.sort_wrestler_by_name
        self.all.sort do |a, b|
            a.name <=> b.name
        end
    end 

    def get_wrestler_favs
        FavoriteWrestler.all.select do |fav|
          fav.wrestler.id == self.id 
        end 
    end 
    
    def wrestler_average_rating
        ratings = get_wrestler_favs.map do |fav|
            fav.rating
        end 
        ratings.sum / ratings.length.to_f
    end 

    def get_wrestler_comments
        wrestler_comments = get_wrestler_favs.map do |fav|
            "#{fav.user.name} commented: #{fav.comments}"
        end 
        wrestler_comments.reverse
    end 

end

app/controllers/wrestlers_controller.rb
class WrestlersController < ApplicationController
    before_action :authorized
    skip_before_action :authorized, only: [:index, :show] 

    def index
        @wrestlers = Wrestler.sort_wrestler_by_name
        get_random_wrestler
    end 

    def show
        get_current_user
        session[:wrestler_id] = params[:id]
        find_wrestler
        get_random_wrestler
    end 

    def new
        @wrestler = Wrestler.new 
    end 

    def create
        @wrestler = Wrestler.new(wrestler_params)
        if @wrestler.valid?
            @wrestler.save
            redirect_to wrestler_path(@wrestler)
        else 
            @errors = @wrestler.errors.full_messages
            render :new
        end 
    end 

    def edit
        find_wrestler
    end

    def update
        find_wrestler.assign_attributes(wrestler_params)
        if @wrestler.valid?
            @wrestler.save
            redirect_to wrestler_path(@wrestler)
        else 
            @errors = @wrestler.errors.full_messages
            render :new
        end 
    end

    private
    def find_wrestler
        @wrestler = Wrestler.find(params[:id])
    end 

    def wrestler_params
        params.require(:wrestler).permit(:name, :bio, :img_url)
    end 

    def get_current_user
        @current_user = User.find_by(id: session[:user_id])
    end 

    def get_random_wrestler
        @random_wrestler = Wrestler.random_sample
    end
end

app/helpers/wrestlers_helper.rb
module WrestlersHelper
end

app/views/wrestlers/edit.html.erb
<h1> Edit <%= @wrestler.name %></h1>

<%if @errors%>
    <%@errors.each do |error|%>
        <p><%=error%></p>
    <%end%>
<%end%>

<%= form_for @wrestler do |f| %>
    <%= f.label :name, 'Wrestler Name:' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :bio, 'Bio:' %><br>
    <%= f.text_area :bio %><br>
    <%= f.label :img_url, 'Image URL:' %><br>
    <%= f.text_field :img_url %><br>
    <%= f.submit %>
<% end %>

<p><%= link_to "Back to Wrestler Profiles", wrestlers_path %> </p>

app/views/wrestlers/index.html.erb
<div class="index">

    <%= link_to "Add New Wrestler!", new_wrestler_path, :class => "ui left attached button" %>
    <%= link_to "Random Wrestler!", wrestler_path(@random_wrestler), :class => "right attached ui button"%>

    <h1> Wrestlers </h1>

    <% @wrestlers.each do |wrestler| %>
    <h3> <%= link_to wrestler.name, wrestler_path(wrestler.id) %> </h3>
    <% end %>

</div>

app/views/wrestlers/new.html.erb
<h1> Add a Wrestler to the Website </h1>

<%if @errors%>
    <%@errors.each do |error|%>
        <p><%=error%></p>
    <%end%>
<%end%>

<%= form_for @wrestler do |f| %>
    <%= f.label :name, 'Wrestler Name:' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :bio, 'Bio:' %><br>
    <%= f.text_area :bio %><br>
    <%= f.label :img_url, 'Image URL:' %><br>
    <%= f.text_field :img_url %><br>
    <%= f.submit %>
<% end %>

<p><%= link_to "Back to Wrestler Profiles", wrestlers_path %> </p>

app/views/wrestlers/show.html.erb
<div class="index">
    <%= link_to "Random Wrestler!", wrestler_path(@random_wrestler), class: "ui button" %>
    <h1>Name: <%= @wrestler.name %></h1>
    <h3>Bio: <%= @wrestler.bio %></h3>
    <h3>Average User Rating: <%= @wrestler.wrestler_average_rating %></h3>
    <img src=<%= @wrestler.img_url %> alt="wrestler" ismap><br>

    <% if @current_user %>
        <%= button_to "Add to Favorites", new_favorite_wrestler_path, method: :get, class: "positive ui button"%><br>
        <p><%= link_to "Edit #{@wrestler.name}", edit_wrestler_path %> </p>
    <% end %>

    <h3>Comment Feed!</h3>
    <% @wrestler.get_wrestler_comments.each do |comment| %>
        <p><%= comment %></p>
    <% end %>
</div>