config/routes.rb
Rails.application.routes.draw do
  resources :moves, except: :destroy
  resources :wrestlers, except: :destroy 
  resources :users
  resources :favorite_moves, only: [:index, :new, :create]
  resources :favorite_wrestlers, only: [:index, :new, :create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/areyousure', to: 'users#areyousure'
  delete '/logout', to: 'sessions#destroy'
  root 'sessions#welcome'



  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite_move.rb
class FavoriteMove < ApplicationRecord
    belongs_to :user
    belongs_to :move
    validates :user_id, :move_id, :rating, :presence => true

end

app/controllers/favorite_moves_controller.rb
class FavoriteMovesController < ApplicationController
    before_action :authorized

    def index
        @favorite_moves = FavoriteMove.all.reverse
    end 

    def new
        @favorite_move = FavoriteMove.new
    end

    def create
        @favorite_move = FavoriteMove.new(user_id: session[:user_id], move_id: session[:move_id])
        @favorite_move.assign_attributes(get_move_params)
        @favorite_move.save
        redirect_to favorite_moves_path
    end 

    private
    def get_move_params
        params.require(:favorite).permit(:rating, :comments)        
    end 
end

app/helpers/favorite_moves_helper.rb
module FavoriteMovesHelper
end

app/views/favorite_moves/index.html.erb
<h1> Favorite Move Feed! </h1>

<ul>
    <% @favorite_moves.each do |fav|%>
        <li>
            <h4><%= "One of #{fav.user.name}'s favorite moves is the #{fav.move.name}. #{fav.user.name} gives it a rating of #{fav.rating} and comments:"  %></h4>
        </li>
        <h4> "<%= "#{fav.comments}" %>" </h4>
        <h3> <%= link_to fav.move.name, move_path(fav.move.id) %> </h3>
        <img src=<%= fav.move.img_url %> alt="move" ><br><br><br><br>
    <% end %>
</ul>

app/views/favorite_moves/new.html.erb
<div class="index">
    <h1> Rate this Move! </h1>

    <%= form_tag '/favorite_moves' do %>
        <%= label_tag 'favorite[rating]', 'Give Move a Rating:' %><br>
        <%= number_field_tag 'favorite[rating]' %><br><br>
        <%= label_tag 'favorite[comments]', 'Say Something About Them:' %><br>
        <%= text_area_tag 'favorite[comments]' %><br><br>
        <%= submit_tag "Add!", class: "ui positive button" %>
    <% end %>
    <br>

    <p><%= link_to "Back to Moves", moves_path %> </p>

</div>